### PR TITLE
feat: Use our own titlebar to avoid double titlebars on Linux/Windows

### LINKED ISSUE #1805: Double titlebars on Windows and Linux
### Bug description

We have double titlebars in Windows and Linux.

The solution is to turn on frameless mode in Electron, which will hide the outer / OS native titlebar, but we need to then implement a titlebar that has minimize, maximize, close (our current one just has the icon + name and no action buttons.)

See https://github.com/containers/podman-desktop/issues/1802 for a design.

### Windows
image

### Linux
Screenshot from 2023-03-23 12-25-41

### Operating system

Windows

### Version

next (development version)

### Steps to reproduce

_No response_

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by benoitf**
Change-Id: I3672a85cf7d777e8744e311e2b9a5abb75aa5c02

### What does this PR do?
Avoid double title bars on Windows and Linux

### Screenshot/screencast of this PR

example on Windows now:
image

### What issues does this PR fix or reference?

fixes https://github.com/containers/podman-desktop/issues/1805

### How to test this PR?

Created so we can get feedback / comments

### CODE REVIEW

**Review by jeffmaury — APPROVED** [review]
LGTM

Tested on Win11Pro

**Comment by deboer-tim** [comment]
Tested on Mac M1, LGTM.

**Comment by benoitf** [comment]
@cdrage so if you can test it under Linux

**Comment by alexojegu** [comment]
Under Linux: https://github.com/containers/podman-desktop/issues/1802#issuecomment-1563372280

**Pull request merged**
